<?php

/*
 *
 *  ____            _        _   __  __ _                  __  __ ____
 * |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \
 * | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) |
 * |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/
 * |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_|
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PocketMine Team
 * @link http://www.pocketmine.net/
 *
 *
*/

declare(strict_types=1);

namespace pocketmine\inventory;

use pocketmine\item\Item;
use pocketmine\network\mcpe\protocol\ProtocolInfo;
use pocketmine\Player;

class PlayerCursorInventory extends BaseInventory{

	/** @var Player */
	protected $holder;

	public function __construct(Player $holder){
		$this->holder = $holder;
		parent::__construct();
	}

	public function getName() : string{
		return "Cursor";
	}

	public function getDefaultSize() : int{
		return 1;
	}

	public function setSize(int $size){
		throw new \BadMethodCallException("Cursor can only carry one item at a time");
	}

    /**
     * @param int $index
     * @return Item
     */
	public function getItem(int $index): Item {
	    if($this->holder->getProtocol() >= ProtocolInfo::PROTOCOL_1_13_0_9) {
            $index = 0; // 1.13+ hack
        }
        return parent::getItem($index);
    }

    /**
     * @param int $index
     * @param Item $item
     * @param bool $send
     *
     * @return bool
     */
    public function setItem(int $index, Item $item, bool $send = true): bool {
        if($this->holder->getProtocol() >= ProtocolInfo::PROTOCOL_1_13_0_9) {
            $index = 0; // 1.13+ hack
        }
        return parent::setItem($index, $item, $send); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $slot
     * @return bool
     */
	public function slotExists(int $slot): bool {
	    if($this->holder->getProtocol() >= ProtocolInfo::PROTOCOL_1_13_0_9) {
	        $slot = 0; // 1.13+ hack
        }
        return parent::slotExists($slot);
    }

    /**
	 * This override is here for documentation and code completion purposes only.
	 * @return Player
	 */
	public function getHolder(){
		return $this->holder;
	}
}
